name: test-dotnet

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - dotnet/**
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - dotnet/**
      - testdata/**
      - .github/**
  workflow_call:

jobs:
  test-dotnet:
    # Failing on `ubuntu-24.04` (https://github.com/cucumber/gherkin/issues/349)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      
      - name: dotnet build
        run: dotnet build -c Release
        working-directory: dotnet

      - name: dotnet test
        run: dotnet test -c Release --no-build
        working-directory: dotnet

      - name: dotnet pack # pack is not required for testing, but it does ensure that the nuget packages can be generated when a new version is released.
        run: dotnet pack -c Release --no-build
        working-directory: dotnet

      - name: run acceptance tests
        run: make acceptance
        working-directory: dotnet
